import type { BattleLayoutConfig, CombatantPanelAnchorConfig, RelativePanelAnchor } from './types';

const anchor = (
  horizontal: RelativePanelAnchor['horizontal'],
  vertical: RelativePanelAnchor['vertical'],
  x: number,
  y: number,
): RelativePanelAnchor => ({ horizontal, vertical, x, y });

const enemyAnchors = (topSeat: boolean): CombatantPanelAnchorConfig => ({
  name: anchor('left', 'top', 18, 18),
  hp: anchor('right', 'top', -118, 18),
  subtitle: anchor('left', 'top', 18, 48),
  cardRow: anchor('left', 'top', 20, 116),
  score: anchor('right', 'top', -42, 57),
  resonance: anchor('left', 'bottom', 20, -26),
  portrait: anchor('right', 'center', -82, 34),
  speech: anchor('left', 'top', 112, 30),
  passive: topSeat ? anchor('left', 'top', -34, 36) : anchor('left', 'top', 34, -32),
  statusPrimary: topSeat ? anchor('left', 'top', -34, 66) : anchor('left', 'top', 34, -2),
  statusAttack: topSeat ? anchor('left', 'top', 38, 84) : anchor('left', 'top', 100, -31),
  talisman: anchor('right', 'top', -42, 54),
  passiveTooltipOffset: topSeat ? { x: -170, y: 104 } : { x: 150, y: -62 },
});

const leftEnemyAnchors: CombatantPanelAnchorConfig = {
  ...enemyAnchors(false),
  cardRow: anchor('left', 'top', 145, 116),
  score: anchor('right', 'top', -42, 57),
  resonance: anchor('left', 'bottom', 145, -26),
  portrait: anchor('left', 'center', 82, 34),
};

export const PC_BATTLE_LAYOUT: BattleLayoutConfig = {
  id: 'pc-1280x720',
  canvas: { width: 1280, height: 720 },
  seats: {
    player: { x: 640, y: 508, width: 330, height: 300 },
    enemies: [
      { x: 245, y: 278, width: 390, height: 190 },
      { x: 640, y: 112, width: 400, height: 190 },
      { x: 1035, y: 278, width: 390, height: 190 },
    ],
  },
  centerInfo: { x: 640, y: 278 },
  stageBanner: { x: 640, y: 278 },
  dealOrigin: { x: 640, y: 330 },
  commandBar: { x: 640, y: 662, width: 520, height: 58 },
  playerControls: {
    item: anchor('left', 'center', -42, 42),
    skills: anchor('right', 'center', 54, -42),
  },
  playerHud: {
    health: { x: -120, y: -132 },
    statuses: { x: 0, y: -108 },
    portrait: { x: -120, y: -36, width: 142, height: 142 },
    name: { x: -120, y: 34 },
    hand: { x: 0, y: -36 },
    handGap: 20,
    utilityBar: { x: 0, y: 70 },
    utilityGap: 56,
    actions: { x: 0, y: 121 },
    scoreGap: 40,
    orbitRadiusX: 84,
    orbitRadiusY: 53,
  },
  enemyHud: {
    left: {
      health: { x: -120, y: -78 },
      statuses: { x: -120, y: 92 },
      portrait: { x: -120, y: 0, width: 142, height: 142 },
      name: { x: -120, y: 70 },
      hand: { x: 68, y: 8 },
      scoreSide: 'right',
      scoreGap: 40,
      speech: { x: -46, y: -116 },
      passivePosition: 'bottom-left',
      orbitRadiusX: 84,
      orbitRadiusY: 53,
    },
    top: {
      health: { x: -120, y: -78 },
      statuses: { x: -120, y: 92 },
      portrait: { x: -120, y: 0, width: 142, height: 142 },
      name: { x: -120, y: 70 },
      hand: { x: 68, y: 8 },
      scoreSide: 'right',
      scoreGap: 40,
      speech: { x: -30, y: 112 },
      passivePosition: 'bottom-left',
      orbitRadiusX: 84,
      orbitRadiusY: 53,
    },
    right: {
      health: { x: 120, y: -78 },
      statuses: { x: 120, y: 92 },
      portrait: { x: 120, y: 0, width: 142, height: 142 },
      name: { x: 120, y: 70 },
      hand: { x: -68, y: 8 },
      scoreSide: 'left',
      scoreGap: 40,
      speech: { x: -140, y: -116 },
      passivePosition: 'bottom-right',
      orbitRadiusX: 84,
      orbitRadiusY: 53,
    },
  },
  hud: {
    logButton: { x: 24, y: 635 },
    exitButton: { x: 1144, y: 635 },
  },
  cards: {
    width: 73,
    spacing: 57,
    enemyWidth: 67,
    enemySpacing: 52,
  },
  combatantPanel: {
    variants: {
      player: {
        name: anchor('left', 'top', 20, 18),
        hp: anchor('right', 'top', -132, 18),
        subtitle: anchor('left', 'top', 18, 48),
        cardRow: anchor('left', 'top', 22, 98),
        score: anchor('right', 'center', -86, 28),
        resonance: anchor('left', 'bottom', 22, -28),
        portrait: anchor('center', 'center', 54, 16),
        speech: anchor('left', 'top', 112, 30),
        passive: anchor('left', 'center', -42, -44),
        statusPrimary: anchor('left', 'top', 34, -2),
        statusAttack: anchor('left', 'top', 100, -31),
        talisman: anchor('right', 'top', -42, 54),
        passiveTooltipOffset: { x: -190, y: -94 },
      },
      'enemy-top': enemyAnchors(true),
      'enemy-left': leftEnemyAnchors,
      'enemy-side': enemyAnchors(false),
    },
    frame: {
      headerHeight: 62,
      headerCenterTopInset: 33,
      headerDividerTopInset: 64,
      horizontalInset: 24,
      contentDividerScoreOffsetX: -48,
      contentDividerY: 30,
      contentDividerMinimumHeight: 72,
      contentDividerHeightInset: 96,
      playerPortraitRadius: 61,
      focusPadding: 8,
      focusMarkerSize: 12,
      focusMarkerGap: 11,
    },
  },
};
