import type { BattleLayoutConfig, CombatantPanelAnchorConfig, RelativePanelAnchor } from './types';

const anchor = (
  horizontal: RelativePanelAnchor['horizontal'],
  vertical: RelativePanelAnchor['vertical'],
  x: number,
  y: number,
): RelativePanelAnchor => ({ horizontal, vertical, x, y });

const enemyAnchors = (topSeat: boolean): CombatantPanelAnchorConfig => ({
  name: anchor('left', 'top', 18, 18),
  hp: anchor('right', 'top', -118, 18),
  subtitle: anchor('left', 'top', 18, 48),
  cardRow: anchor('left', 'top', 20, 116),
  score: anchor('right', 'top', -42, 57),
  resonance: anchor('left', 'bottom', 20, -26),
  portrait: anchor('right', 'center', -82, 34),
  speech: anchor('left', 'top', 112, 30),
  passive: topSeat ? anchor('left', 'top', -34, 36) : anchor('left', 'top', 34, -32),
  statusPrimary: topSeat ? anchor('left', 'top', -34, 66) : anchor('left', 'top', 34, -2),
  statusAttack: topSeat ? anchor('left', 'top', 38, 84) : anchor('left', 'top', 100, -31),
  talisman: anchor('right', 'top', -42, 54),
  passiveTooltipOffset: topSeat ? { x: -170, y: 104 } : { x: 150, y: -62 },
});

const leftEnemyAnchors: CombatantPanelAnchorConfig = {
  ...enemyAnchors(false),
  cardRow: anchor('left', 'top', 145, 116),
  score: anchor('right', 'top', -42, 57),
  resonance: anchor('left', 'bottom', 145, -26),
  portrait: anchor('left', 'center', 82, 34),
};

export const PC_BATTLE_LAYOUT: BattleLayoutConfig = {
  id: 'pc-1280x720',
  canvas: { width: 1280, height: 720 },
  seats: {
    player: { x: 640, y: 448, width: 520, height: 240 },
    enemies: [
      { x: 270, y: 290, width: 340, height: 300 },
      { x: 640, y: 116, width: 380, height: 300 },
      { x: 1010, y: 290, width: 340, height: 300 },
    ],
  },
  centerInfo: { x: 640, y: 322 },
  stageBanner: { x: 640, y: 322 },
  dealOrigin: { x: 640, y: 330 },
  commandBar: { x: 640, y: 634, width: 520, height: 58 },
  playerControls: {
    item: anchor('left', 'center', -42, 42),
    skills: anchor('right', 'center', 54, -42),
  },
  playerHud: {
    health: { x: 0, y: -96 },
    statuses: { x: 0, y: -58 },
    portrait: { x: 0, y: 0, width: 142, height: 154 },
    name: { x: 0, y: 63 },
    hand: { x: 0, y: 132 },
    actions: { x: 0, y: 204 },
    scoreGap: 42,
    orbitRadiusX: 88,
    orbitRadiusY: 50,
  },
  enemyHud: {
    left: {
      health: { x: 0, y: -96 },
      statuses: { x: 0, y: -58 },
      portrait: { x: 0, y: 0, width: 142, height: 154 },
      name: { x: 0, y: 63 },
      hand: { x: 0, y: 137 },
      scoreSide: 'right',
      scoreGap: 30,
      speech: { x: 50, y: -112 },
      passivePosition: 'bottom-left',
      orbitRadiusX: 88,
      orbitRadiusY: 50,
    },
    top: {
      health: { x: 0, y: -96 },
      statuses: { x: 0, y: -58 },
      portrait: { x: 0, y: 0, width: 142, height: 154 },
      name: { x: 0, y: 63 },
      hand: { x: 0, y: 137 },
      scoreSide: 'right',
      scoreGap: 30,
      speech: { x: -80, y: -112 },
      passivePosition: 'top-right',
      orbitRadiusX: 88,
      orbitRadiusY: 50,
    },
    right: {
      health: { x: 0, y: -96 },
      statuses: { x: 0, y: -58 },
      portrait: { x: 0, y: 0, width: 142, height: 154 },
      name: { x: 0, y: 63 },
      hand: { x: 0, y: 137 },
      scoreSide: 'right',
      scoreGap: 30,
      speech: { x: -150, y: -112 },
      passivePosition: 'top-right',
      orbitRadiusX: 88,
      orbitRadiusY: 50,
    },
  },
  hud: {
    logButton: { x: 24, y: 116 },
    exitButton: { x: 1128, y: 116 },
  },
  cards: {
    width: 70,
    spacing: 54,
  },
  combatantPanel: {
    variants: {
      player: {
        name: anchor('left', 'top', 20, 18),
        hp: anchor('right', 'top', -132, 18),
        subtitle: anchor('left', 'top', 18, 48),
        cardRow: anchor('left', 'top', 22, 98),
        score: anchor('right', 'center', -86, 28),
        resonance: anchor('left', 'bottom', 22, -28),
        portrait: anchor('center', 'center', 54, 16),
        speech: anchor('left', 'top', 112, 30),
        passive: anchor('left', 'center', -42, -44),
        statusPrimary: anchor('left', 'top', 34, -2),
        statusAttack: anchor('left', 'top', 100, -31),
        talisman: anchor('right', 'top', -42, 54),
        passiveTooltipOffset: { x: -190, y: -94 },
      },
      'enemy-top': enemyAnchors(true),
      'enemy-left': leftEnemyAnchors,
      'enemy-side': enemyAnchors(false),
    },
    frame: {
      headerHeight: 62,
      headerCenterTopInset: 33,
      headerDividerTopInset: 64,
      horizontalInset: 24,
      contentDividerScoreOffsetX: -48,
      contentDividerY: 30,
      contentDividerMinimumHeight: 72,
      contentDividerHeightInset: 96,
      playerPortraitRadius: 61,
      focusPadding: 8,
      focusMarkerSize: 12,
      focusMarkerGap: 11,
    },
  },
};
