const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.QA_PLAYWRIGHT_MODULE||'playwright');const {runtime}=require('../../tests/helpers/typescript-runtime.cjs');
const url=process.env.QA_BASE_URL||'http://127.0.0.1:5179',output=process.env.QA_OUTPUT||'tmp/readability';fs.mkdirSync(output,{recursive:true});
function seed(){const r=runtime({saved:{soulCoins:500,ownedItems:{heal_potion:2}}});return JSON.parse(JSON.stringify(r.progress.getProgress()));}
async function labels(page){return page.evaluate(()=>{const out=[];function visit(n){if(n.visible===false||n.active===false)return;if(n.type==='Text'){const m=n.getWorldTransformMatrix();out.push({text:n.text,x:m.tx+(0.5-n.originX)*n.width,y:m.ty+(0.5-n.originY)*n.height,style:n.style?.fontSize});}if(n.list)n.list.forEach(visit);}qaGame.scene.getScenes(true).forEach(s=>s.children.list.forEach(visit));return out;});}
async function click(page,text){const nodes=(await labels(page)).filter(n=>n.text===text);assert.equal(nodes.length,1,'Missing/ambiguous '+text);await page.mouse.click(nodes[0].x,nodes[0].y);await page.waitForTimeout(150);}
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.QA_CHROME_PATH?{executablePath:process.env.QA_CHROME_PATH}:{})});const report={checks:[],errors:[],missingAssets:[]};try{const context=await browser.newContext({viewport:{width:1280,height:720}});await context.addInitScript(save=>localStorage.setItem('one-more-card-progress',JSON.stringify(save)),seed());const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));page.on('response',r=>{if(r.status()>=400)report.missingAssets.push(r.url())});await page.route('**/src/main.ts*',async route=>{const response=await route.fetch(),body=await response.text();await route.fulfill({response,body:body.replace('new Phaser.Game(config)','globalThis.qaGame = new Phaser.Game(config)')});});await page.goto(url);await page.waitForFunction(()=>globalThis.qaGame?.scene.getScene('StartScene')?.sys.isActive());
await page.evaluate(()=>qaGame.scene.getScene('StartScene').scene.start('BattleScene',{mode:'story',levelId:'chapter1_9'}));await page.waitForFunction(()=>qaGame.scene.getScene('BattleScene')?.battle);await page.waitForFunction(()=>{const s=qaGame.scene.getScene('BattleScene');return s&&!s.isPresentationBusy()},{timeout:20000});
await page.evaluate(()=>{const s=qaGame.scene.getScene('BattleScene');s.shownLevelIntroLesson=true;s.blockingMessage=undefined;s.graduationTutorialStep=0;s.render();});
const first=await labels(page);assert(first.some(n=>n.text==='下一步'&&n.style==='19px'));await page.screenshot({path:path.join(output,'chapter-five-next-button.png')});await click(page,'下一步');assert((await labels(page)).some(n=>n.text==='下一步'));report.checks.push('Chapter five Next renders as a real interactive medieval button and advances');
await page.evaluate(()=>{const s=qaGame.scene.getScene('BattleScene');s.graduationTutorialStep=7;s.render();});assert((await labels(page)).some(n=>n.text==='开始自由行动'));await page.screenshot({path:path.join(output,'chapter-five-free-action-button.png')});await click(page,'开始自由行动');assert.equal(await page.evaluate(()=>qaGame.scene.getScene('BattleScene').graduationTutorialStep),8);report.checks.push('Free action CTA renders as a button and closes the guide');
await page.evaluate(()=>{const s=qaGame.scene.getScene('BattleScene');s.showSkillTooltip(640,300,'共鸣转换','将一张异色牌转换为多数花色，使手牌形成共鸣。冷却2轮。',true);});const tooltip=await labels(page);assert(tooltip.some(n=>n.text.startsWith('将一张')&&n.style==='16px'));await page.screenshot({path:path.join(output,'skill-tooltip-large.png')});report.checks.push('Shared skill/status/item tooltip body is 16px');
await page.evaluate(()=>{const s=qaGame.scene.getScene('BattleScene');s.hideSkillTooltip();s.battle.phase='player-turn';s.itemModalOpen=true;s.render();});await page.waitForTimeout(900);const item=await labels(page);assert(item.some(n=>n.text.includes('回复3点生命')&&n.style==='15px'));await page.screenshot({path:path.join(output,'battle-item-description-large.png')});report.checks.push('Battle item-card description is 15px with expanded card height');
await context.close();assert.deepEqual(report.errors,[]);assert.deepEqual(report.missingAssets,[]);report.passed=true;}finally{fs.writeFileSync(path.join(output,'browser-report.json'),JSON.stringify(report,null,2));await browser.close();}console.log(JSON.stringify(report,null,2));})().catch(e=>{console.error(e);process.exitCode=1});
